# SPDX-FileCopyrightText: 2021 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

# Build the manager binary
FROM golang:1.17 as builder

WORKDIR /workspace/parser-sdk/go
COPY . .
# Skip build (to be done by parser)
